/**
 * @file index.js
 * @description Centralized JSDoc type definitions for the AgenticForge frontend.
 * Provides type safety and intellisense without migrating to TypeScript.
 */

/**
 * @typedef {Object} StreamEvent
 * @property {'node_start'|'node_finish'|'interrupted'|'error'|'sandbox_output'|'complete'} type - The event category.
 * @property {string} [node] - The specific LangGraph node involved (e.g., 'planner', 'coder', 'reviewer').
 * @property {Record<string, any>} [state] - The current AgentState diff payload (e.g., plan string, code snippet, reviewer_feedback).
 * @property {string} [message] - An optional human-readable status message for the UI logger.
 */

/**
 * @typedef {Object} ForgeResponse
 * @property {string} plan - The step-by-step technical plan generated by the AI.
 * @property {string} code - The final generated code.
 * @property {number} iterations - Number of iterations it took to generate and review the code.
 * @property {WorkspaceFile[]} [workspace_files] - The list of files generated in the workspace.
 */

/**
 * @typedef {Object} ProjectResponse
 * @property {number} id - Project ID.
 * @property {number} user_id - The ID of the user who owns this project.
 * @property {string} thread_id - Thread UUID for the LangGraph workflow.
 * @property {string} created_at - ISO 8601 datetime string.
 * @property {string} user_prompt - The initial prompt provided by the user.
 * @property {string} [final_plan] - The final technical plan.
 * @property {string} [final_code] - The final generated code.
 * @property {number} iterations_taken - Iterations consumed.
 * @property {number} total_tokens - Total tokens consumed.
 */

/**
 * @typedef {Object} BillingStatus
 * @property {string} subscription_tier - The active subscription tier (e.g., 'Free Developer' or 'pro_architect').
 * @property {boolean} is_active - Whether the account is active/unsuspended.
 */

/**
 * @typedef {Object} User
 * @property {number} id - The user's ID.
 * @property {string} email - The user's email address.
 * @property {string} name - The user's display name.
 * @property {string} [subscription_tier] - The user's subscription tier.
 * @property {boolean} [is_active] - Account status.
 */

/**
 * @typedef {Object} AuthToken
 * @property {string} access_token - The JWT access token.
 * @property {string} refresh_token - The JWT refresh token.
 * @property {string} token_type - "bearer".
 * @property {User} user - The authenticated user object.
 */

/**
 * @typedef {Object} WorkspaceFile
 * @property {string} filename - The relative path or filename.
 * @property {string} content - The code content.
 * @property {string} [language] - The programming language identifier (e.g., 'python', 'javascript').
 */

export {}; // Ensures this file is treated as an ES module by JS parsers
