"""Add user_id to Project

Revision ID: 2fee0b835458
Revises: 4802af4bf6b4
Create Date: 2026-06-18 22:13:43.725652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fee0b835458'
down_revision: Union[str, Sequence[str], None] = '4802af4bf6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_projects_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_tier', sa.String(), server_default='Free Developer', nullable=False))
        batch_op.add_column(sa.Column('llm_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_api_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_subscription_tier'), ['subscription_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_subscription_tier'))
        batch_op.drop_column('encrypted_api_key')
        batch_op.drop_column('llm_provider')
        batch_op.drop_column('subscription_tier')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_thread_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_date'))

    op.drop_table('token_usage')
    # ### end Alembic commands ###
