"""Add thread_id to Project

Revision ID: 4802af4bf6b4
Revises: 66588f377dae
Create Date: 2026-06-17 22:54:46.546290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4802af4bf6b4'
down_revision: Union[str, Sequence[str], None] = '66588f377dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thread_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_thread_id'), 'projects', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_thread_id'), table_name='projects')
    op.drop_column('projects', 'thread_id')
    # ### end Alembic commands ###
