from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID
from app.schemas.streaming import StreamEvent

class ForgeRequest(BaseModel):
    prompt: str = Field(..., description="The user's prompt or request for code generation")
    thread_id: Optional[UUID] = Field(default=None, description="Optional thread ID to continue an existing conversation")

class ResumeRequest(BaseModel):
    thread_id: UUID = Field(..., description="The thread ID of the paused workflow to resume")
    human_feedback: Optional[str] = Field(
        default=None,
        description=(
            "Optional human feedback to inject into the state before the reviewer runs. "
            "If omitted, the graph resumes with the coder's draft unchanged."
        )
    )

class ForgeResponse(BaseModel):
    plan: str = Field(..., description="The step-by-step technical plan generated by the AI")
    code: str = Field(..., description="The final generated code")
    workspace_files: list[dict] = Field(default_factory=list, description="List of generated workspace files")
    iterations: int = Field(..., description="Number of iterations it took to generate and review the code")

class ThreadHistoryResponse(BaseModel):
    thread_id: UUID = Field(..., description="The thread ID")
    history: list[StreamEvent] = Field(default_factory=list, description="List of historical state snapshots")
